### ISSUE TITLE
clear-sources  update

### ISSUE THREAD

**Issue by antonellocaroli** [gentoobr/overlay#30]
Excuse my question, but is clear-sources still being updated or has it been abandoned?

Thanks

**Comment by capezotte** [comment]
Unfortunately I've been neglecting this package. I've pushed the ebuild for the non-LTS Clear Linux kernel, and see if I can make the script I use to generate them run from a cronjob.

I couldn't make LTS ebuilds because Gentoo and Clear Linux are currently greatly out of sync (Clear's ltscurrent is 6.6.8, while Gentoo's it at 6.6.30). I don't know how to handle this.

**Comment by antonellocaroli** [comment]
Thanks for the reply, but I more meant for the non-LTS versions.

for example 6.8.9

**Comment by capezotte** [comment]
I improved the script so it copes better with the scenario of the Gentoo patchset and the Clear patchset being out of sync. Updates should be more timely now.
